### ISSUE TITLE
transform table to cards

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/resources#1]
The following information should be included in cards:

file url
sha256
classifier's Artifact UUID
date added
citation(s)
sklearn version
submitter's Forum handle
notes (optional)
link where more info can be found (optional)

**Comment by Oddant1** [comment]
@gregcaporaso for date added, is that date we added it to this page?

**Comment by gregcaporaso** [comment]
That's what I was thinking, but maybe more relevant now that you're asking is "Date trained", which we could find in the data provenance. Let's do that instead.

**Comment by Oddant1** [comment]
I was thinking along the same lines

**Comment by Oddant1** [comment]
@gregcaporaso and @ebolyen unfun unexciting question, how do we want the dates formatted? I popped open the prov and we have this:

```
runtime:
    start: 2021-05-05T17:55:38.775177-07:00
    end: 2021-05-09T18:19:10.486732-07:00
    duration: 4 days, 23 minutes, 31 seconds, and 711555 microseconds
```

I'm inclined to use the end time, but do we want it in ISO format like that? Do we want it in American mm/dd/yyyy or dd/mm/yyyy? My inclination is to leave it in ISO format, but sometimes I think like a computer not a normal person.
